Pamphlet
biocommons/hackathon-2023 pull request #18
Opened 2023-09-08 12:21 UTC by jsstevenson

2023-09-08 12:33 UTC, korikuzma requested changes

2023-09-08 12:33 UTC, korikuzma commented on pamphlet/agenda.md
> +| 8:45 | Arrival &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |
Can we include the comment about not arriving later than this time?

2023-09-08 12:33 UTC, korikuzma commented on pamphlet/agenda.md
> +| 12:00 | Lunch break |
Include [Delarosa Pizza](https://www.delarosasf.com/location/downtown/)

2023-09-08 12:33 UTC, korikuzma commented on pamphlet/agenda.md
> +| 18:30 | Dinner at Chateau de Reece |
Include [Truly Mediterranean](https://www.trulyeats.com/catering-menu) wraps, platters, and kababs

2023-09-08 12:33 UTC, korikuzma commented on pamphlet/agenda.md
> +| 12:30 | Lunch break |
Include [Uno dos tacos](https://order.toasttab.com/online/uno-dos-tacos)

2023-09-08 12:34 UTC, korikuzma commented
@reece You had made a note about too much going on at the end on day 1. What (if any) changes were you thinking?

2023-09-08 12:50 UTC, korikuzma requested changes

2023-09-08 12:50 UTC, korikuzma commented on pamphlet/agenda.pdf
Is it possible to make this one page? If we need to cut something, I think it's fine excluding the reason why we don't want people arriving late (can include this reason in slack channel)

2023-09-08 13:21 UTC, jsstevenson commented on pamphlet/agenda.pdf
@korikuzma Adding the full "please arrive" text puts it onto two pages, I'll just do a short version

2023-09-08 13:29 UTC, korikuzma commented on pamphlet/agenda.pdf
Sorry for all the requests. Can we have it be "latest time to arrive by" ?

2023-09-08 14:15 UTC, jsstevenson commented on pamphlet/agenda.pdf
As in

```
| 8:45 | Arrival (latest time to arrive by) &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |
```

?

2023-09-08 14:18 UTC, korikuzma commented on pamphlet/agenda.pdf
I was just thinking this

```markdown
| 8:45 | Latest time to arrive by &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp;&nbsp; &nbsp; &nbsp; &nbsp; &nbsp; &nbsp; |
```

2023-09-08 14:19 UTC, korikuzma commented on pamphlet/agenda.pdf
Or maybe just changing it to like 8:55 for the start time? Idk

2023-09-08 14:22 UTC, korikuzma commented on pamphlet/agenda.pdf
@reece what do you think?

2023-09-13 16:29 UTC, korikuzma commented
Closing, we're moving to google doc with these changes

2023-09-13 16:29 UTC, closed without merging